/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: x4VgG6kzZCVuaqknYN7tgc
// Component: GKHfm0W5wVuv

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: x4VgG6kzZCVuaqknYN7tgc/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: x4VgG6kzZCVuaqknYN7tgc/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: x4VgG6kzZCVuaqknYN7tgc/projectcss
import sty from "./PlasmicFooterPixel.module.css"; // plasmic-import: GKHfm0W5wVuv/css

createPlasmicElementProxy;

export type PlasmicFooterPixel__VariantMembers = {};
export type PlasmicFooterPixel__VariantsArgs = {};
type VariantPropType = keyof PlasmicFooterPixel__VariantsArgs;
export const PlasmicFooterPixel__VariantProps = new Array<VariantPropType>();

export type PlasmicFooterPixel__ArgsType = {};
type ArgPropType = keyof PlasmicFooterPixel__ArgsType;
export const PlasmicFooterPixel__ArgProps = new Array<ArgPropType>();

export type PlasmicFooterPixel__OverridesType = {
  root?: Flex__<"div">;
  columns?: Flex__<"div">;
  disuko?: Flex__<"a"> & Partial<LinkProps>;
  freeBox?: Flex__<"div">;
};

export interface DefaultFooterPixelProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicFooterPixel__RenderFunc(props: {
  variants: PlasmicFooterPixel__VariantsArgs;
  args: PlasmicFooterPixel__ArgsType;
  overrides: PlasmicFooterPixel__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const currentUser = useCurrentUser?.() || {};

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"columns"}
        data-plasmic-override={overrides.columns}
        className={classNames(projectcss.all, sty.columns)}
      >
        <div className={classNames(projectcss.all, sty.column__dcmGr)}>
          <PlasmicLink__
            data-plasmic-name={"disuko"}
            data-plasmic-override={overrides.disuko}
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.a__x4VgG,
              sty.disuko
            )}
            component={Link}
            href={`/`}
            legacyBehavior={false}
            platform={"nextjs"}
            target={"_blank"}
          >
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__mnLpD)}
              displayHeight={"100%"}
              displayMaxHeight={"none"}
              displayMaxWidth={"none"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/disuko_website_retro_version/images/disukoPandaPixelPng.png",
                fullWidth: 480,
                fullHeight: 480,
                aspectRatio: undefined
              }}
            />
          </PlasmicLink__>
        </div>
        <div className={classNames(projectcss.all, sty.column__xXVm)}>
          <div
            data-plasmic-name={"freeBox"}
            data-plasmic-override={overrides.freeBox}
            className={classNames(projectcss.all, sty.freeBox)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__b9EpP
              )}
            >
              <React.Fragment>
                <span
                  className={
                    "plasmic_default__all plasmic_default__span plasmic_default__span__x4VgG"
                  }
                  style={{ fontWeight: 400 }}
                >
                  {"website \u00a9 disuko & "}
                </span>
                <React.Fragment>{""}</React.Fragment>
                {
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.a__x4VgG,
                      projectcss.__wab_text,
                      projectcss.plasmic_default__inline,
                      sty.link__cAAi
                    )}
                    component={Link}
                    href={"https://redpandamedia.net"}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    <React.Fragment>
                      <span
                        className={
                          "plasmic_default__all plasmic_default__span plasmic_default__span__x4VgG"
                        }
                        style={{ fontWeight: 400 }}
                      >
                        {"Red Panda Studios"}
                      </span>
                    </React.Fragment>
                  </PlasmicLink__>
                }
                <React.Fragment>{""}</React.Fragment>
                <span
                  className={
                    "plasmic_default__all plasmic_default__span plasmic_default__span__x4VgG"
                  }
                  style={{ fontWeight: 400 }}
                >
                  {" 2023"}
                </span>
              </React.Fragment>
            </div>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.a__x4VgG,
                sty.link___13BKz
              )}
              component={Link}
              href={"https://www.ohhey.gay/gay-gives"}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___6UtX)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"56px"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/disuko_website_retro_version/images/dotGayRgbPng.png",
                  fullWidth: 210,
                  fullHeight: 92,
                  aspectRatio: undefined
                }}
              />
            </PlasmicLink__>
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.column__uupEl)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__liHz
            )}
          >
            <React.Fragment>
              <React.Fragment>{"icons from "}</React.Fragment>
              {
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.a__x4VgG,
                    projectcss.__wab_text,
                    projectcss.plasmic_default__inline,
                    sty.link__dhsma
                  )}
                  component={Link}
                  href={"https://github.com/konradkalemba/tabler-icons-react"}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  {"tabler"}
                </PlasmicLink__>
              }
              <React.Fragment>{""}</React.Fragment>
            </React.Fragment>
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "columns", "disuko", "freeBox"],
  columns: ["columns", "disuko", "freeBox"],
  disuko: ["disuko"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  columns: "div";
  disuko: "a";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFooterPixel__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFooterPixel__VariantsArgs;
    args?: PlasmicFooterPixel__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicFooterPixel__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicFooterPixel__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicFooterPixel__ArgProps,
          internalVariantPropNames: PlasmicFooterPixel__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFooterPixel__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFooterPixel";
  } else {
    func.displayName = `PlasmicFooterPixel.${nodeName}`;
  }
  return func;
}

export const PlasmicFooterPixel = Object.assign(
  // Top-level PlasmicFooterPixel renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    columns: makeNodeComponent("columns"),
    disuko: makeNodeComponent("disuko"),
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicFooterPixel
    internalVariantProps: PlasmicFooterPixel__VariantProps,
    internalArgProps: PlasmicFooterPixel__ArgProps
  }
);

export default PlasmicFooterPixel;
/* prettier-ignore-end */
