/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: x4VgG6kzZCVuaqknYN7tgc
// Component: jITmhNWlDefq

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";

import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";

import Navbar from "../../Navbar"; // plasmic-import: 5THU1wffFibB/component
import WindowButton from "../../WindowButton"; // plasmic-import: KZYdo-R8GYAn/component
import Window from "../../Window"; // plasmic-import: BWjgdOwFY_OO/component
import Footer from "../../Footer"; // plasmic-import: shKoGjSwLEEB/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: x4VgG6kzZCVuaqknYN7tgc/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: x4VgG6kzZCVuaqknYN7tgc/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: x4VgG6kzZCVuaqknYN7tgc/projectcss
import sty from "./PlasmicCommissions.module.css"; // plasmic-import: jITmhNWlDefq/css

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    title: "🌸disuko - Commissions",
    description:
      "Commissions by disuko, featuring design, 3D modelling, and music production. ",
    openGraph: {
      title: "🌸disuko - Commissions",
      description:
        "Commissions by disuko, featuring design, 3D modelling, and music production. "
    },
    twitter: {
      card: "summary" as const,
      title: "🌸disuko - Commissions",
      description:
        "Commissions by disuko, featuring design, 3D modelling, and music production. "
    },
    alternates: { canonical: "https://disuko.gay/commissions" }
  };
}

createPlasmicElementProxy;

export type PlasmicCommissions__VariantMembers = {};
export type PlasmicCommissions__VariantsArgs = {};
type VariantPropType = keyof PlasmicCommissions__VariantsArgs;
export const PlasmicCommissions__VariantProps = new Array<VariantPropType>();

export type PlasmicCommissions__ArgsType = {};
type ArgPropType = keyof PlasmicCommissions__ArgsType;
export const PlasmicCommissions__ArgProps = new Array<ArgPropType>();

export type PlasmicCommissions__OverridesType = {
  root?: Flex__<"div">;
  navbar?: Flex__<typeof Navbar>;
  windowButton?: Flex__<typeof WindowButton>;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultCommissionsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCommissions__RenderFunc(props: {
  variants: PlasmicCommissions__VariantsArgs;
  args: PlasmicCommissions__ArgsType;
  overrides: PlasmicCommissions__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const currentUser = useCurrentUser?.() || {};

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />
        <meta
          key="description"
          property="description"
          content={pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={pageMetadata.description}
        />
        <meta
          key="twitter:description"
          property="twitter:description"
          content={pageMetadata.description}
        />

        <link rel="canonical" href={pageMetadata.alternates?.canonical} />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root,
            {
              [sty.rootglobal_theme_classic]: hasVariant(
                globalVariants,
                "theme",
                "classic"
              )
            }
          )}
        >
          <Navbar
            data-plasmic-name={"navbar"}
            data-plasmic-override={overrides.navbar}
            className={classNames("__wab_instance", sty.navbar)}
          />

          <div className={classNames(projectcss.all, sty.freeBox__hYSzg)}>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img___2B3YC)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "100%"
                  : "75%"
              }
              loading={"lazy"}
              src={{
                src: "/plasmic/disuko_website_retro_version/images/wordart2Png.png",
                fullWidth: 1797,
                fullHeight: 564,
                aspectRatio: undefined
              }}
            />

            <WindowButton
              data-plasmic-name={"windowButton"}
              data-plasmic-override={overrides.windowButton}
              className={classNames("__wab_instance", sty.windowButton)}
              link={"https://forms.gle/Hn1Kkf176DsSgawG9"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__nmYig,
                  {
                    [sty.textglobal_theme_classic__nmYiGeNktM]: hasVariant(
                      globalVariants,
                      "theme",
                      "classic"
                    )
                  }
                )}
              >
                {"Request Form + Info"}
              </div>
            </WindowButton>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__za4GN,
                {
                  [sty.textglobal_theme_classic__za4GNeNktM]: hasVariant(
                    globalVariants,
                    "theme",
                    "classic"
                  )
                }
              )}
            >
              {"Pricing Estimates + Basic Details"}
            </div>
            <div className={classNames(projectcss.all, sty.columns__u2Lre)}>
              <div className={classNames(projectcss.all, sty.column__qyp8)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__yhfEx,
                    {
                      [sty.textglobal_theme_classic__yhfEXeNktM]: hasVariant(
                        globalVariants,
                        "theme",
                        "classic"
                      )
                    }
                  )}
                >
                  {"2D Design"}
                </div>
                <Window
                  className={classNames("__wab_instance", sty.window__bGvUm)}
                  showImage={true}
                  windowImage={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__qfXr, {
                        [sty.imgglobal_theme_classic__qfXrENktM]: hasVariant(
                          globalVariants,
                          "theme",
                          "classic"
                        )
                      })}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "100%"
                          : "354px"
                      }
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/disuko_website_retro_version/images/ddsLogoPng2.png",
                        fullWidth: 1271,
                        fullHeight: 622,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  windowText={"One-Off Logo: $20"}
                  windowTitle={"2D Design"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bHG,
                      {
                        [sty.textglobal_theme_classic__bHGeNktM]: hasVariant(
                          globalVariants,
                          "theme",
                          "classic"
                        )
                      }
                    )}
                  >
                    {"Social Media Icon, Sticker Design, Game Logo, etc."}
                  </div>
                </Window>
                <Window
                  className={classNames("__wab_instance", sty.window__gl6Ht)}
                  showImage={true}
                  windowImage={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__tltl1, {
                        [sty.imgglobal_theme_classic__tltl1ENktM]: hasVariant(
                          globalVariants,
                          "theme",
                          "classic"
                        )
                      })}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "100%"
                          : "354px"
                      }
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/disuko_website_retro_version/images/image30.png",
                        fullWidth: 4400,
                        fullHeight: 5600,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  windowText={"Poster: $40"}
                  windowTitle={"2D Design"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aAapR,
                      {
                        [sty.textglobal_theme_classic__aAapReNktM]: hasVariant(
                          globalVariants,
                          "theme",
                          "classic"
                        )
                      }
                    )}
                  >
                    {"Music Event Poster, Poster Design for Printing"}
                  </div>
                </Window>
                <Window
                  className={classNames("__wab_instance", sty.window__rJrJ7)}
                  showImage={true}
                  windowImage={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__bc6M8, {
                        [sty.imgglobal_theme_classic__bc6M8ENktM]: hasVariant(
                          globalVariants,
                          "theme",
                          "classic"
                        )
                      })}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "100%"
                          : "354px"
                      }
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/disuko_website_retro_version/images/honeyTeaaaBrandSheetPng.png",
                        fullWidth: 2480,
                        fullHeight: 3508,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  windowText={"Logo + Simple Brand Kit: $60"}
                  windowTitle={"2D Design"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__exCeu,
                      {
                        [sty.textglobal_theme_classic__exCeueNktM]: hasVariant(
                          globalVariants,
                          "theme",
                          "classic"
                        )
                      }
                    )}
                  >
                    {
                      "Social Media Brand Kit, Twitch Overlay, Website Assets, etc."
                    }
                  </div>
                </Window>
              </div>
              <div className={classNames(projectcss.all, sty.column___2OlL9)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kZp8C,
                    {
                      [sty.textglobal_theme_classic__kZp8CeNktM]: hasVariant(
                        globalVariants,
                        "theme",
                        "classic"
                      )
                    }
                  )}
                >
                  {"3D Design"}
                </div>
                <Window
                  className={classNames("__wab_instance", sty.window___8G18Z)}
                  showImage={true}
                  windowImage={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__jGHr, {
                        [sty.imgglobal_theme_classic__jGHreNktM]: hasVariant(
                          globalVariants,
                          "theme",
                          "classic"
                        )
                      })}
                      displayHeight={"231px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "100%"
                          : "354px"
                      }
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/disuko_website_retro_version/images/toastFinalWebSizePng.png",
                        fullWidth: 768,
                        fullHeight: 768,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  windowText={"Simple Model - $20"}
                  windowTitle={"3D Design"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ct6M0,
                      {
                        [sty.textglobal_theme_classic__ct6M0ENktM]: hasVariant(
                          globalVariants,
                          "theme",
                          "classic"
                        )
                      }
                    )}
                  >
                    {"Simple Character, Object"}
                  </div>
                </Window>
                <Window
                  className={classNames("__wab_instance", sty.window__xXtNw)}
                  showImage={true}
                  windowImage={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___8SmNd, {
                        [sty.imgglobal_theme_classic___8SmNdeNktM]: hasVariant(
                          globalVariants,
                          "theme",
                          "classic"
                        )
                      })}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "100%"
                          : "354px"
                      }
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/disuko_website_retro_version/images/frogWebp.webp",
                        fullWidth: 256,
                        fullHeight: 189,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  windowText={"Complex Model / Simple Scene- $50"}
                  windowTitle={"3D Design"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kfdg,
                      {
                        [sty.textglobal_theme_classic__kfdgENktM]: hasVariant(
                          globalVariants,
                          "theme",
                          "classic"
                        )
                      }
                    )}
                  >
                    {"Simple Character, Simple Environment, 1-2 Props"}
                  </div>
                </Window>
                <Window
                  className={classNames("__wab_instance", sty.window__nZzKy)}
                  showImage={true}
                  windowImage={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___1Aowu, {
                        [sty.imgglobal_theme_classic___1AowueNktM]: hasVariant(
                          globalVariants,
                          "theme",
                          "classic"
                        )
                      })}
                      displayHeight={"325px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "100%"
                          : "354px"
                      }
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/disuko_website_retro_version/images/animestreetWebp.webp",
                        fullWidth: 800,
                        fullHeight: 1422,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  windowText={"Full Scene - $200"}
                  windowTitle={"3D Design"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eytyP,
                      {
                        [sty.textglobal_theme_classic__eytyPeNktM]: hasVariant(
                          globalVariants,
                          "theme",
                          "classic"
                        )
                      }
                    )}
                  >
                    {"Full Background, Many Props, Simple Character"}
                  </div>
                </Window>
                <Window
                  className={classNames("__wab_instance", sty.window__n50M)}
                  showImage={true}
                  windowImage={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__t9DiA, {
                        [sty.imgglobal_theme_classic__t9DiAeNktM]: hasVariant(
                          globalVariants,
                          "theme",
                          "classic"
                        )
                      })}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "100%"
                          : "354px"
                      }
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/disuko_website_retro_version/images/image67.gif",
                        fullWidth: 600,
                        fullHeight: 338,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  windowText={
                    "Full 3D Character- $300 (REQUIRES FRONT AND SIDE REF SHEET)"
                  }
                  windowTitle={"3D Design"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bdJBs,
                      {
                        [sty.textglobal_theme_classic__bdJBseNktM]: hasVariant(
                          globalVariants,
                          "theme",
                          "classic"
                        )
                      }
                    )}
                  >
                    {
                      "Full 3D Character w/ Rig, VRChat Avatar Base, Video Game Character, Vtuber Avatar Base, etc."
                    }
                  </div>
                </Window>
              </div>
              <div
                className={classNames(projectcss.all, sty.column__aScra, {
                  [sty.columnglobal_theme_classic__aScraeNktM]: hasVariant(
                    globalVariants,
                    "theme",
                    "classic"
                  )
                })}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hu5Qu,
                    {
                      [sty.textglobal_theme_classic__hu5QueNktM]: hasVariant(
                        globalVariants,
                        "theme",
                        "classic"
                      )
                    }
                  )}
                >
                  {"Audio"}
                </div>
                <Window
                  className={classNames("__wab_instance", sty.window__ga2Wt)}
                  showImage={true}
                  windowImage={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__qgQUs, {
                        [sty.imgglobal_theme_classic__qgQUseNktM]: hasVariant(
                          globalVariants,
                          "theme",
                          "classic"
                        )
                      })}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "100%"
                          : "354px"
                      }
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/disuko_website_retro_version/images/mixerPng.png",
                        fullWidth: 1597,
                        fullHeight: 418,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  windowText={"Mini Track- $10"}
                  windowTitle={"Music"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qv2TC,
                      {
                        [sty.textglobal_theme_classic__qv2TCeNktM]: hasVariant(
                          globalVariants,
                          "theme",
                          "classic"
                        )
                      }
                    )}
                  >
                    {
                      "Studio Intro Jingle, Video Game Sound Effect, 10-30 seconds"
                    }
                  </div>
                </Window>
                <Window
                  className={classNames("__wab_instance", sty.window__mKkHq)}
                  showImage={true}
                  windowImage={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__crTu, {
                        [sty.imgglobal_theme_classic__crTueNktM]: hasVariant(
                          globalVariants,
                          "theme",
                          "classic"
                        )
                      })}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "100%"
                          : "354px"
                      }
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/disuko_website_retro_version/images/mixerPng.png",
                        fullWidth: 1597,
                        fullHeight: 418,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  windowText={"Short Track - $75"}
                  windowTitle={"Music"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__il6Bk,
                      {
                        [sty.textglobal_theme_classic__il6BkeNktM]: hasVariant(
                          globalVariants,
                          "theme",
                          "classic"
                        )
                      }
                    )}
                  >
                    {
                      "Video Game Background Music, Youtube Intro/Outro 60-90 seconds"
                    }
                  </div>
                </Window>
                <Window
                  className={classNames("__wab_instance", sty.window__kor0)}
                  showImage={true}
                  windowImage={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___1AbcC, {
                        [sty.imgglobal_theme_classic___1AbcCeNktM]: hasVariant(
                          globalVariants,
                          "theme",
                          "classic"
                        )
                      })}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "100%"
                          : "354px"
                      }
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/disuko_website_retro_version/images/mixerPng.png",
                        fullWidth: 1597,
                        fullHeight: 418,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  windowText={"Full Track - $150"}
                  windowTitle={"Music"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bk1Ht,
                      {
                        [sty.textglobal_theme_classic__bk1HteNktM]: hasVariant(
                          globalVariants,
                          "theme",
                          "classic"
                        )
                      }
                    )}
                  >
                    {
                      "Full Track for Release, Rhythm Game Track, Short Film Music, 2-3 Minutes"
                    }
                  </div>
                </Window>
              </div>
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__kr28D,
                {
                  [sty.textglobal_theme_classic__kr28DeNktM]: hasVariant(
                    globalVariants,
                    "theme",
                    "classic"
                  )
                }
              )}
            >
              {"Current Commissions Progress"}
            </div>
            <div className={classNames(projectcss.all, sty.columns__arCte)}>
              <div className={classNames(projectcss.all, sty.column__nwOqx)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___43Ac,
                    {
                      [sty.textglobal_theme_classic___43AceNktM]: hasVariant(
                        globalVariants,
                        "theme",
                        "classic"
                      )
                    }
                  )}
                >
                  {"Queue"}
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___6SyU, {
                    [sty.freeBoxglobal_theme_classic___6SyUeNktM]: hasVariant(
                      globalVariants,
                      "theme",
                      "classic"
                    )
                  })}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__ozfWe)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___4DZZn,
                    {
                      [sty.textglobal_theme_classic___4DZZneNktM]: hasVariant(
                        globalVariants,
                        "theme",
                        "classic"
                      )
                    }
                  )}
                >
                  {"WIP"}
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___6EVmN, {
                    [sty.freeBoxglobal_theme_classic___6EVmNeNktM]: hasVariant(
                      globalVariants,
                      "theme",
                      "classic"
                    )
                  })}
                >
                  <Window
                    className={classNames("__wab_instance", sty.window___64NmC)}
                    linkDestination={""}
                    showImage={true}
                    windowImage={
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__tn5Pv, {
                          [sty.imgglobal_theme_classic__tn5PVeNktM]: hasVariant(
                            globalVariants,
                            "theme",
                            "classic"
                          )
                        })}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/disuko_website_retro_version/images/image70.png",
                          fullWidth: 509,
                          fullHeight: 524,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    windowText={"TeaSona Character for @hiveandhearth.cafe"}
                    windowTitle={"3D - TeaSona"}
                  />
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__p1BVq)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rEoIg,
                    {
                      [sty.textglobal_theme_classic__rEoIgeNktM]: hasVariant(
                        globalVariants,
                        "theme",
                        "classic"
                      )
                    }
                  )}
                >
                  {"Complete"}
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox__oxqpO, {
                    [sty.freeBoxglobal_theme_classic__oxqpOeNktM]: hasVariant(
                      globalVariants,
                      "theme",
                      "classic"
                    )
                  })}
                >
                  <Window
                    className={classNames(
                      "__wab_instance",
                      sty.window___5AZoh,
                      {
                        [sty.windowglobal_theme_classic___5AZoHeNktM]:
                          hasVariant(globalVariants, "theme", "classic")
                      }
                    )}
                    showImage={true}
                    windowImage={
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__ilXxZ, {
                          [sty.imgglobal_theme_classic__ilXxZeNktM]: hasVariant(
                            globalVariants,
                            "theme",
                            "classic"
                          )
                        })}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/disuko_website_retro_version/images/image73.png",
                          fullWidth: 1189,
                          fullHeight: 814,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    windowText={
                      "Red Crown Brand Kit for https://redcrown.events"
                    }
                    windowTitle={"2D - Red Crown Brand Kit"}
                  />

                  <Window
                    className={classNames("__wab_instance", sty.window__orzP)}
                    showImage={true}
                    windowImage={
                      <React.Fragment>
                        <Window
                          className={classNames(
                            "__wab_instance",
                            sty.window__s5L5J
                          )}
                          showImage={true}
                          windowImage={
                            <PlasmicImg__
                              alt={""}
                              className={classNames(sty.img__q5QTw)}
                              displayHeight={"auto"}
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              loading={"lazy"}
                              src={{
                                src: "/plasmic/disuko_website_retro_version/images/ezgifComOptimizeGif.gif",
                                fullWidth: 1920,
                                fullHeight: 1080,
                                aspectRatio: undefined
                              }}
                            />
                          }
                          windowText={"3D Office Props for @voidred.dev"}
                          windowTitle={"Office Props"}
                        />

                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__z18Xo, {
                            [sty.imgglobal_theme_classic__z18XoeNktM]:
                              hasVariant(globalVariants, "theme", "classic")
                          })}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/disuko_website_retro_version/images/image71.png",
                            fullWidth: 658,
                            fullHeight: 627,
                            aspectRatio: undefined
                          }}
                        />
                      </React.Fragment>
                    }
                    windowText={"Sherbert Puppycat Character"}
                    windowTitle={"3D - Sherbert"}
                  />

                  <Window
                    className={classNames("__wab_instance", sty.window__cnHUk)}
                    showImage={true}
                    windowImage={
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__gtnmw, {
                          [sty.imgglobal_theme_classic__gtnmweNktM]: hasVariant(
                            globalVariants,
                            "theme",
                            "classic"
                          )
                        })}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/disuko_website_retro_version/images/image72.png",
                          fullWidth: 1920,
                          fullHeight: 1080,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    windowText={"Polaroid Scene Template for @rustybeefus"}
                    windowTitle={"3D - Polaroid Scene"}
                  />

                  <Window
                    className={classNames("__wab_instance", sty.window__pPwv7, {
                      [sty.windowglobal_theme_classic__pPwv7ENktM]: hasVariant(
                        globalVariants,
                        "theme",
                        "classic"
                      )
                    })}
                    showImage={true}
                    windowImage={
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__vgM, {
                          [sty.imgglobal_theme_classic__vgMENktM]: hasVariant(
                            globalVariants,
                            "theme",
                            "classic"
                          )
                        })}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/disuko_website_retro_version/images/image101.png",
                          fullWidth: 2048,
                          fullHeight: 1260,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    windowText={
                      "Logo for https://www.instagram.com/millzflips/"
                    }
                    windowTitle={"2D - Millz Flips Logo"}
                  />
                </div>
              </div>
            </div>
          </div>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer, {
              [sty.footerglobal_theme_classic]: hasVariant(
                globalVariants,
                "theme",
                "classic"
              )
            })}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "navbar", "windowButton", "footer"],
  navbar: ["navbar"],
  windowButton: ["windowButton"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  navbar: typeof Navbar;
  windowButton: typeof WindowButton;
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCommissions__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCommissions__VariantsArgs;
    args?: PlasmicCommissions__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicCommissions__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicCommissions__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCommissions__ArgProps,
          internalVariantPropNames: PlasmicCommissions__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCommissions__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCommissions";
  } else {
    func.displayName = `PlasmicCommissions.${nodeName}`;
  }
  return func;
}

function withUsePlasmicAuth<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const WithUsePlasmicAuthComponent: React.FC<P> = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "x4VgG6kzZCVuaqknYN7tgc"
    });

    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicCommissions = Object.assign(
  // Top-level PlasmicCommissions renders the root element
  withUsePlasmicAuth(makeNodeComponent("root")),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    windowButton: makeNodeComponent("windowButton"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicCommissions
    internalVariantProps: PlasmicCommissions__VariantProps,
    internalArgProps: PlasmicCommissions__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/commissions",
      pagePath: "/commissions",
      params: {},
      query: {}
    })
  }
);

export default PlasmicCommissions;
/* prettier-ignore-end */
