/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: x4VgG6kzZCVuaqknYN7tgc
// Component: FM3_GOS4-xG4

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";

import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";

import Navbar from "../../Navbar"; // plasmic-import: 5THU1wffFibB/component
import Window from "../../Window"; // plasmic-import: BWjgdOwFY_OO/component
import ImageWindow from "../../ImageWindow"; // plasmic-import: cCfEU_zMoOP5/component
import WindowButton from "../../WindowButton"; // plasmic-import: KZYdo-R8GYAn/component
import Footer from "../../Footer"; // plasmic-import: shKoGjSwLEEB/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: x4VgG6kzZCVuaqknYN7tgc/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: x4VgG6kzZCVuaqknYN7tgc/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: x4VgG6kzZCVuaqknYN7tgc/projectcss
import sty from "./PlasmicPortfolio.module.css"; // plasmic-import: FM3_GOS4-xG4/css

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    title: "disuko - portfolio🌸",
    description:
      "~all of my completed /ongoing work, including music, 3D, design, and video.",
    openGraph: {
      title: "disuko - portfolio🌸",
      description:
        "~all of my completed /ongoing work, including music, 3D, design, and video.",
      images: [
        "https://site-assets.plasmic.app/f33b16e8e3629b301959c659f5c8f11d.jpg"
      ]
    },
    twitter: {
      card: "summary_large_image" as const,
      title: "disuko - portfolio🌸",
      description:
        "~all of my completed /ongoing work, including music, 3D, design, and video.",
      images: [
        "https://site-assets.plasmic.app/f33b16e8e3629b301959c659f5c8f11d.jpg"
      ]
    },
    alternates: { canonical: "https://disuko.gay/portfolio" }
  };
}

createPlasmicElementProxy;

export type PlasmicPortfolio__VariantMembers = {};
export type PlasmicPortfolio__VariantsArgs = {};
type VariantPropType = keyof PlasmicPortfolio__VariantsArgs;
export const PlasmicPortfolio__VariantProps = new Array<VariantPropType>();

export type PlasmicPortfolio__ArgsType = {};
type ArgPropType = keyof PlasmicPortfolio__ArgsType;
export const PlasmicPortfolio__ArgProps = new Array<ArgPropType>();

export type PlasmicPortfolio__OverridesType = {
  root?: Flex__<"div">;
  navbar?: Flex__<typeof Navbar>;
  main?: Flex__<"div">;
  imageWindow?: Flex__<typeof ImageWindow>;
  columns?: Flex__<"div">;
  imm?: Flex__<"div">;
  webDesign?: Flex__<"div">;
  link?: Flex__<"a"> & Partial<LinkProps>;
  _3DDesign?: Flex__<"div">;
  music?: Flex__<"div">;
  _2DDesign?: Flex__<"div">;
  film?: Flex__<"div">;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultPortfolioProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPortfolio__RenderFunc(props: {
  variants: PlasmicPortfolio__VariantsArgs;
  args: PlasmicPortfolio__ArgsType;
  overrides: PlasmicPortfolio__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const currentUser = useCurrentUser?.() || {};

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />
        <meta
          key="description"
          property="description"
          content={pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={pageMetadata.description}
        />
        <meta
          key="twitter:description"
          property="twitter:description"
          content={pageMetadata.description}
        />
        <meta
          key="og:image"
          property="og:image"
          content={pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          property="twitter:image"
          content={pageMetadata.ogImageSrc}
        />
        <link rel="canonical" href={pageMetadata.alternates?.canonical} />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root,
            {
              [sty.rootglobal_theme_classic]: hasVariant(
                globalVariants,
                "theme",
                "classic"
              )
            }
          )}
        >
          <Navbar
            data-plasmic-name={"navbar"}
            data-plasmic-override={overrides.navbar}
            className={classNames("__wab_instance", sty.navbar)}
          />

          <div
            data-plasmic-name={"main"}
            data-plasmic-override={overrides.main}
            className={classNames(projectcss.all, sty.main, {
              [sty.mainglobal_theme_classic]: hasVariant(
                globalVariants,
                "theme",
                "classic"
              )
            })}
          >
            <div className={classNames(projectcss.all, sty.freeBox__iNumN)}>
              <div className={classNames(projectcss.all, sty.freeBox__s1Xm)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__au15O)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/disuko_website_retro_version/images/wordartPng2.png",
                    fullWidth: 1797,
                    fullHeight: 430,
                    aspectRatio: undefined
                  }}
                />

                <Window
                  className={classNames("__wab_instance", sty.window__a9Ns)}
                  linkDestination={`/IMM`}
                  windowImage={null}
                  windowText={
                    "Hi! I\u2019m Angelo, and I\u2019m an enthusiast for everything having to do with digital technology. I\u2019m currently studying Immersive Media, Music Technology, and Film & Digital Media Production at Chatham University. I also make content online as \u201cDisuko.\u201d my main goal is sharing the truest form of myself with any medium available! At the core of my work is using technology to share my emotions, viewpoints, and interests. "
                  }
                  windowTitle={"about me"}
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__yDuY)}>
                <ImageWindow
                  data-plasmic-name={"imageWindow"}
                  data-plasmic-override={overrides.imageWindow}
                  className={classNames("__wab_instance", sty.imageWindow, {
                    [sty.imageWindowglobal_theme_classic]: hasVariant(
                      globalVariants,
                      "theme",
                      "classic"
                    )
                  })}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__y5U8J)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/disuko_website_retro_version/images/headShot2025SmallJpg.jpg",
                      fullWidth: 1748,
                      fullHeight: 1166,
                      aspectRatio: undefined
                    }}
                  />
                </ImageWindow>
                <div className={classNames(projectcss.all, sty.freeBox__a9Bbt)}>
                  <WindowButton
                    className={classNames(
                      "__wab_instance",
                      sty.windowButton__oX6B
                    )}
                    link={
                      "https://drive.google.com/drive/folders/1VesaOi3VAPvbhMWhtLeT0ZD5d66nWwow?usp=drive_link"
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dcKO,
                        {
                          [sty.textglobal_theme_classic__dcKOeNktM]: hasVariant(
                            globalVariants,
                            "theme",
                            "classic"
                          )
                        }
                      )}
                    >
                      {"Download Resume"}
                    </div>
                  </WindowButton>
                  <WindowButton
                    className={classNames(
                      "__wab_instance",
                      sty.windowButton___6RFoD
                    )}
                    link={"mailto:angelo@disuko.gay"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__goaQ6,
                        {
                          [sty.textglobal_theme_classic__goaQ6ENktM]:
                            hasVariant(globalVariants, "theme", "classic")
                        }
                      )}
                    >
                      {"Contact"}
                    </div>
                  </WindowButton>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"columns"}
              data-plasmic-override={overrides.columns}
              className={classNames(projectcss.all, sty.columns)}
            >
              <div
                data-plasmic-name={"imm"}
                data-plasmic-override={overrides.imm}
                className={classNames(projectcss.all, sty.imm)}
              >
                <Window
                  className={classNames("__wab_instance", sty.window__p6Lhm)}
                  linkDestination={`/IMM`}
                  windowImage={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__qwXj9)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/disuko_website_retro_version/images/dsc8618Jpg.jpg",
                        fullWidth: 5568,
                        fullHeight: 3712,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  windowText={
                    "Unity Engine / Godot Engine / TouchDesigner / Arduino"
                  }
                  windowTitle={"Immersive Media"}
                />
              </div>
              <div
                data-plasmic-name={"webDesign"}
                data-plasmic-override={overrides.webDesign}
                className={classNames(projectcss.all, sty.webDesign)}
              >
                <Window
                  children={null}
                  className={classNames("__wab_instance", sty.window__b4HY)}
                  linkDestination={"https://disuko.cloud"}
                  windowImage={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__lHzoC)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/disuko_website_retro_version/images/screenshot20260510194928Png.png",
                        fullWidth: 1717,
                        fullHeight: 920,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  windowText={
                    "Plasmic, TypeScript, React, Node.js, HTML, Javascript, CSS"
                  }
                  windowTitle={"Web Design"}
                />

                <PlasmicLink__
                  data-plasmic-name={"link"}
                  data-plasmic-override={overrides.link}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.a__x4VgG,
                    projectcss.__wab_text,
                    sty.link
                  )}
                  component={Link}
                  href={"https://disuko.cloud"}
                  legacyBehavior={false}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  {"NEW WEBSITE UNDER CONSTRUCTION"}
                </PlasmicLink__>
              </div>
              <div
                data-plasmic-name={"_3DDesign"}
                data-plasmic-override={overrides._3DDesign}
                className={classNames(projectcss.all, sty._3DDesign)}
              >
                <Window
                  className={classNames("__wab_instance", sty.window__iSq4J)}
                  linkDestination={`/3d-design`}
                  windowImage={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__v0XiG)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/disuko_website_retro_version/images/teacupFrogWorkflowJpg.jpg",
                        fullWidth: 1920,
                        fullHeight: 1080,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  windowText={"Blender / Maya / Fusion 360"}
                  windowTitle={"3D Design"}
                />
              </div>
              <div
                data-plasmic-name={"music"}
                data-plasmic-override={overrides.music}
                className={classNames(projectcss.all, sty.music)}
              >
                <Window
                  className={classNames("__wab_instance", sty.window__cifFm)}
                  linkDestination={`/music`}
                  windowImage={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__u2Kt)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/disuko_website_retro_version/images/angeloDJingJpg.jpg",
                        fullWidth: 1920,
                        fullHeight: 1080,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  windowText={
                    "FL Studio / Ableton Live/ BitWig Studio / Adobe Audition"
                  }
                  windowTitle={"Music"}
                />
              </div>
              <div
                data-plasmic-name={"_2DDesign"}
                data-plasmic-override={overrides._2DDesign}
                className={classNames(projectcss.all, sty._2DDesign)}
              >
                <Window
                  className={classNames("__wab_instance", sty.window__tlLqO)}
                  linkDestination={`/2d-design`}
                  windowImage={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__kMwug)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/disuko_website_retro_version/images/zineCroppedPng.png",
                        fullWidth: 1920,
                        fullHeight: 1080,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  windowText={"Adobe Photoshop / Illustrator"}
                  windowTitle={"2D Design"}
                />
              </div>
              <div
                data-plasmic-name={"film"}
                data-plasmic-override={overrides.film}
                className={classNames(projectcss.all, sty.film)}
              >
                <Window
                  className={classNames("__wab_instance", sty.window__oqDxY)}
                  linkDestination={`/film`}
                  windowImage={
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__azDap)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/disuko_website_retro_version/images/vlcsnap2025042401H05M47S151Png.png",
                        fullWidth: 3840,
                        fullHeight: 2160,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  windowText={
                    "Adobe Premiere / After Effects / Davinci Resolve"
                  }
                  windowTitle={"Film"}
                />
              </div>
            </div>
          </div>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navbar",
    "main",
    "imageWindow",
    "columns",
    "imm",
    "webDesign",
    "link",
    "_3DDesign",
    "music",
    "_2DDesign",
    "film",
    "footer"
  ],
  navbar: ["navbar"],
  main: [
    "main",
    "imageWindow",
    "columns",
    "imm",
    "webDesign",
    "link",
    "_3DDesign",
    "music",
    "_2DDesign",
    "film"
  ],
  imageWindow: ["imageWindow"],
  columns: [
    "columns",
    "imm",
    "webDesign",
    "link",
    "_3DDesign",
    "music",
    "_2DDesign",
    "film"
  ],
  imm: ["imm"],
  webDesign: ["webDesign", "link"],
  link: ["link"],
  _3DDesign: ["_3DDesign"],
  music: ["music"],
  _2DDesign: ["_2DDesign"],
  film: ["film"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  navbar: typeof Navbar;
  main: "div";
  imageWindow: typeof ImageWindow;
  columns: "div";
  imm: "div";
  webDesign: "div";
  link: "a";
  _3DDesign: "div";
  music: "div";
  _2DDesign: "div";
  film: "div";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPortfolio__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPortfolio__VariantsArgs;
    args?: PlasmicPortfolio__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicPortfolio__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicPortfolio__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPortfolio__ArgProps,
          internalVariantPropNames: PlasmicPortfolio__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPortfolio__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPortfolio";
  } else {
    func.displayName = `PlasmicPortfolio.${nodeName}`;
  }
  return func;
}

function withUsePlasmicAuth<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const WithUsePlasmicAuthComponent: React.FC<P> = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "x4VgG6kzZCVuaqknYN7tgc"
    });

    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicPortfolio = Object.assign(
  // Top-level PlasmicPortfolio renders the root element
  withUsePlasmicAuth(makeNodeComponent("root")),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    main: makeNodeComponent("main"),
    imageWindow: makeNodeComponent("imageWindow"),
    columns: makeNodeComponent("columns"),
    imm: makeNodeComponent("imm"),
    webDesign: makeNodeComponent("webDesign"),
    link: makeNodeComponent("link"),
    _3DDesign: makeNodeComponent("_3DDesign"),
    music: makeNodeComponent("music"),
    _2DDesign: makeNodeComponent("_2DDesign"),
    film: makeNodeComponent("film"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicPortfolio
    internalVariantProps: PlasmicPortfolio__VariantProps,
    internalArgProps: PlasmicPortfolio__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/portfolio",
      pagePath: "/portfolio",
      params: {},
      query: {}
    })
  }
);

export default PlasmicPortfolio;
/* prettier-ignore-end */
