// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicBlurredPicture,
  DefaultBlurredPictureProps
} from "./plasmic/disuko_website_retro_version/PlasmicBlurredPicture";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface BlurredPictureProps extends Omit<DefaultBlurredPictureProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultBlurredPictureProps altogether and have
// total control over the props for your component.
export interface BlurredPictureProps extends DefaultBlurredPictureProps {}

function BlurredPicture_(
  props: BlurredPictureProps,
  ref: HTMLElementRefOf<"div">
) {
  // Use PlasmicBlurredPicture to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicBlurredPicture are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all BlurredPictureProps here, but feel free
  // to do whatever works for you.

  return <PlasmicBlurredPicture root={{ ref }} {...props} />;
}

const BlurredPicture = React.forwardRef(BlurredPicture_);
export default BlurredPicture;
